
//
// Dimensions.swift
//

// Do not edit directly, this file was auto-generated.


import UIKit

public struct Dimensions {
    public static let refSpace0 = CGFloat(0.00)
    public static let refSpace2xl = CGFloat(40.00)
    public static let refSpace2xs = CGFloat(4.00)
    public static let refSpace3xl = CGFloat(48.00)
    public static let refSpace3xs = CGFloat(2.00)
    public static let refSpace4xl = CGFloat(64.00)
    public static let refSpace4xs = CGFloat(1.00)
    public static let refSpace5xl = CGFloat(80.00)
    public static let refSpace6xl = CGFloat(96.00)
    public static let refSpace7xl = CGFloat(112.00)
    public static let refSpace8xl = CGFloat(120.00)
    public static let refSpaceL = CGFloat(24.00)
    public static let refSpaceM = CGFloat(16.00)
    public static let refSpaceMax = CGFloat(999.00)
    public static let refSpaceS = CGFloat(12.00)
    public static let refSpaceXl = CGFloat(32.00)
    public static let refSpaceXs = CGFloat(8.00)
    public static let sysSpace0 = CGFloat(0.00)
    public static let sysSpace2xl = CGFloat(40.00)
    public static let sysSpace2xs = CGFloat(4.00)
    public static let sysSpace3xl = CGFloat(48.00)
    public static let sysSpace3xs = CGFloat(2.00)
    public static let sysSpace4xl = CGFloat(64.00)
    public static let sysSpace4xs = CGFloat(1.00)
    public static let sysSpace5xl = CGFloat(80.00)
    public static let sysSpace6xl = CGFloat(96.00)
    public static let sysSpace7xl = CGFloat(112.00)
    public static let sysSpace8xl = CGFloat(120.00)
    public static let sysSpaceL = CGFloat(24.00)
    public static let sysSpaceM = CGFloat(16.00)
    public static let sysSpaceMax = CGFloat(999.00)
    public static let sysSpaceS = CGFloat(12.00)
    public static let sysSpaceXl = CGFloat(32.00)
    public static let sysSpaceXs = CGFloat(8.00)
    public static let sysTextLineHeightBodyL = CGFloat(26.00)
    public static let sysTextLineHeightBodyM = CGFloat(24.00)
    public static let sysTextLineHeightBodyS = CGFloat(20.00)
    public static let sysTextLineHeightDetailM = CGFloat(20.00)
    public static let sysTextLineHeightDetailS = CGFloat(18.00)
    public static let sysTextLineHeightDetailXs = CGFloat(16.00)
    public static let sysTextLineHeightDisplay2xl = CGFloat(90.00)
    public static let sysTextLineHeightDisplayL = CGFloat(56.00)
    public static let sysTextLineHeightDisplayM = CGFloat(44.00)
    public static let sysTextLineHeightDisplayS = CGFloat(40.00)
    public static let sysTextLineHeightDisplayXl = CGFloat(72.00)
    public static let sysTextLineHeightHeading2xs = CGFloat(20.00)
    public static let sysTextLineHeightHeadingL = CGFloat(40.00)
    public static let sysTextLineHeightHeadingM = CGFloat(32.00)
    public static let sysTextLineHeightHeadingS = CGFloat(28.00)
    public static let sysTextLineHeightHeadingXl = CGFloat(44.00)
    public static let sysTextLineHeightHeadingXs = CGFloat(24.00)
    public static let sysTextLineHeightPreamble2xl = CGFloat(40.00)
    public static let sysTextLineHeightPreambleL = CGFloat(32.00)
    public static let sysTextLineHeightPreambleM = CGFloat(28.00)
    public static let sysTextLineHeightPreambleS = CGFloat(26.00)
    public static let sysTextLineHeightPreambleXl = CGFloat(36.00)
    public static let sysTextLineHeightPreambleXs = CGFloat(24.00)
    public static let sysTextSizeBodyL = CGFloat(20.00)
    public static let sysTextSizeBodyM = CGFloat(16.00)
    public static let sysTextSizeBodyS = CGFloat(14.00)
    public static let sysTextSizeDetailM = CGFloat(16.00)
    public static let sysTextSizeDetailS = CGFloat(14.00)
    public static let sysTextSizeDetailXs = CGFloat(12.00)
    public static let sysTextSizeDisplay2xl = CGFloat(82.00)
    public static let sysTextSizeDisplayL = CGFloat(48.00)
    public static let sysTextSizeDisplayM = CGFloat(36.00)
    public static let sysTextSizeDisplayS = CGFloat(32.00)
    public static let sysTextSizeDisplayXl = CGFloat(64.00)
    public static let sysTextSizeHeading2xl = CGFloat(14.00)
    public static let sysTextSizeHeading2xs = CGFloat(14.00)
    public static let sysTextSizeHeadingL = CGFloat(28.00)
    public static let sysTextSizeHeadingM = CGFloat(24.00)
    public static let sysTextSizeHeadingS = CGFloat(20.00)
    public static let sysTextSizeHeadingXl = CGFloat(32.00)
    public static let sysTextSizeHeadingXs = CGFloat(16.00)
    public static let sysTextSizePreamble2xl = CGFloat(32.00)
    public static let sysTextSizePreambleL = CGFloat(24.00)
    public static let sysTextSizePreambleM = CGFloat(20.00)
    public static let sysTextSizePreambleS = CGFloat(18.00)
    public static let sysTextSizePreambleXl = CGFloat(28.00)
    public static let sysTextSizePreambleXs = CGFloat(16.00)
}